version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 8000:3000
    command: yarn dev
    volumes:
      - .:/app
  db:
    image: mysql:5.7.23
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  bundle:
  mysql_data:
